In [6]:
b = [1,2,3]
an_apple = 52
print("dodo")

def add_numbers(a,b):
    """"Sum 2 values"""
    return a+b
add_numbers(1,2)

list(range(5, 0, -1))
seq = [7, 2, 3, 7, 5, 6, 0, 1]

print(seq[::-1])


dodo
[1, 0, 6, 5, 7, 3, 2, 7]


In [ ]:
strings = ['a', 'as', 'bat', 'car', 'dove', 'python']
[x.upper() for x in strings if len(x) > 2]
print(b)

loc_mapping = {val:index for index, val in enumerate(strings)}
loc_mapping

[1, 2, 3]


{'a': 0, 'as': 1, 'bat': 2, 'car': 3, 'dove': 4, 'python': 5}

In [8]:
all_data = [['John','Emily','Michael','Mary','Steven'],
            ['Maria','Juan','Javier','Natalia','Pilar']]
names_of_interest =[]
result = [name for names in all_data for name in names if name.count('a') >= 2]
print(result)

['Maria', 'Natalia']


In [11]:
some_tuples = [(1, 2, 3), (4, 5, 6), (7, 8, 9)]
flattened = [x for tup in some_tuples for x in tup]
print(flattened)

[[x for x in tup] for tup in some_tuples]


[1, 2, 3, 4, 5, 6, 7, 8, 9]


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
states = ['   Alabama', 'Georgia!', 'Georgia',
           'georgia', 'FlOrIda','south   carolina##', 'West virginia?']

import re
def clean_strings(strings):
    result=[]
    for value in strings:
        values = value.strip()
        value = re.sub('[!#?]','',value)
        value = value.title()
        result.append(value)
    return result

def remove_punctuation(value):
    return re.sub('[!#?]','',value)
clean_ops = [str.strip, remove_punctuation, str.title]

def clean_strings(strings, ops):
    result =[]
    for value in strings:
        for function in ops:
            value = function(value)
        result.append(value)
    return result

clean_strings(states, clean_ops)

equiv_annon = lambda x: x*2

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']

In [8]:
def apply_to_list(some_list, f):
    return [f(x) for x in some_list]

ints =[4, 0, 1, 5, 6]
apply_to_list(ints, lambda x: x*2)

[8, 0, 2, 10, 12]

In [10]:
import itertools

def first_letter(x):
    return x[0]

names = ['Alan', 'Adam', 'Wes', 'Will', 'Albert', 'Steven']

for letter, names in itertools.groupby(names, first_letter):
    print(letter, list(names))

A ['Alan', 'Adam']
W ['Wes', 'Will']
A ['Albert']
S ['Steven']


In [6]:
path ='segismundo.txt'
f = open(path, encoding= "utf-8")

with open(path, encoding= "utf-8") as f:
    lines = [x.strip for x in f]
    print(lines)

[<built-in method strip of str object at 0x0000026EFE53EA00>]


In [1]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x*2 for x in my_list]

CPU times: total: 15.6 ms
Wall time: 16 ms
CPU times: total: 422 ms
Wall time: 428 ms


In [15]:
import numpy as np
data = np.array([[1.5, -0.3,3],[0, -3, 6.5]])
data

data *10
data+data

data1 =[6, 7, 8, 0, 1]
arr1 = np.array(data1)

arr1

data2 =[[1, 2, 3, 4],[5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

arr1.dtype
arr2.dtype

np.zeros(10)
np.zeros((3,6))
np.empty((2,3,2))
np.arange(15)

arr1.dtype
float64_arr = arr1.astype(np.float64)
float64_arr.dtype


arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10,1])
arr

arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10,  1], dtype=int32)

In [5]:
import numpy as np
arr = np.array([[1., 2., 3.],[4.,5.,6.]])
arr
arr2 = arr*arr
arr-arr2
arr > arr2

array([[False, False, False],
       [False, False, False]])

In [13]:
import numpy as np
arr = np.arange(10)
arr_slice = arr[5:8]
arr[5:8] = 12
arr


arr_slice

arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [13]:
import numpy as np
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2d[2]

arr3d = np.array([[[1, 2, 3],[4, 5, 6]], [[7, 8, 9],[10, 11, 12]]])

arr3d[0]
old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d
arr3d[0] = old_values
arr3d[1, 0]
x = arr3d[1]
x
x[0]
lower_dim_slice = arr2d[1,:2]
lower_dim_slice.shape
arr2d[:2,2]
arr2d[:2,1:]
arr2d[2:, :]
arr2d[:,:2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [35]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob','Will', 'Joe','Joe' ])
data = np.array([[4,7],[0,2],[-5,6],[0,0],[1,2],[-12,-4],[3,4]])
names
data
data[names =='Bob', 1:]
data[names == 'Bob',1]
names !='Bob'
mask = (names =='Bob') | (names == 'Will')
mask

data[names =='Bob']
data[mask]
data[data<0] =0
data

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])