In [1]:
import numpy as np
import pandas as pd
import json
np.random.seed(12345)
import matplotlib.pyplot as plt
plt.rc('figure', figsize=(10, 6))
PREVIOUS_MAX_ROWS = pd.options.display.max_rows
pd.options.display.max_columns = 20
pd.options.display.max_rows = 20
pd.options.display.max_colwidth = 80
np.set_printoptions(precision=4, suppress=True)

In [6]:
rng = np.random.default_rng(seed=12345)
np.ones((10,5)).shape
np.ones((3,4,5), dtype=np.float64).strides

(160, 40, 8)

In [9]:
ints = np.ones(10,dtype=np.uint16)
floats = np.ones(10,dtype=np.float32)
np.issubdtype(ints.dtype, np.integer)
np.issubdtype(floats.dtype, np.floating)
np.float64.mro()
np.issubdtype(ints.dtype, np.number)

True

In [18]:
arr = np.arange(8)
arr
arr.reshape((4,2))
arr.reshape((4,2)).reshape((2,4))
arr = np.arange(15)
arr.reshape((5,-1))
other_arr = np.ones((3,5))
other_arr.shape
arr.reshape(other_arr.shape)
arr = np.arange(15).reshape((5,3))
arr
arr.ravel()
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
arr = np.arange(12).reshape((3,4))
arr
arr.ravel()
arr.ravel('F')

array([ 0,  4,  8,  1,  5,  9,  2,  6, 10,  3,  7, 11])

In [33]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
np.concatenate([arr1,arr2],axis=0)
np.concatenate([arr1, arr2], axis=1)
np.vstack((arr1,arr2))
np.hstack((arr1,arr2))
arr = rng.standard_normal((5,2))
arr
first, second, third = np.split(arr, [1,3])
first
second
third

array([[0.136 , 1.3471],
       [0.0611, 0.0709]])

In [36]:
arr = np.arange(6)
arr1 = arr.reshape((3,2))
arr2 = rng.standard_normal((3,2))
np.r_[arr1,arr2]
np.c_[np.r_[arr1,arr2],arr]
np.c_[1:6,-10:-5]

array([[  1, -10],
       [  2,  -9],
       [  3,  -8],
       [  4,  -7],
       [  5,  -6]])

In [41]:
arr = np.arange(3)
arr
arr.repeat(3)
arr.repeat([2,3,4])
arr = rng.standard_normal((2,2))
arr
arr.repeat(2,axis=0)

array([[ 0.0071,  0.5344],
       [ 0.0071,  0.5344],
       [-1.0658, -0.1815],
       [-1.0658, -0.1815]])

In [ ]:
arr.repeat([2,3],axis=0)
arr.repeat([2,3], axis=1)


AttributeError: 'numpy.ndarray' object has no attribute 'tile'

In [54]:
arr = np.arange(10)*100
inds = [7,1,2,6]
arr[inds]
arr.take(inds)
arr.put(inds,42)
arr
arr.put(inds,[40,41,42,43])
arr
inds =[2,0,2,1]
arr =np.random.randn(2,4)
arr
arr.take(inds,axis=1)

array([[1.0072, 0.769 , 1.0072, 1.2464],
       [1.3529, 0.275 , 1.3529, 0.2289]])

In [64]:
arr = np.arange(5)
arr
arr *4
arr = rng.standard_normal((4,3))
arr.mean(0)
demeaned = arr-arr.mean(0)
demeaned
demeaned.mean(0)
arr
row_means = arr.mean(1)
row_means.shape
row_means.reshape((4,1))
demeaned = arr - row_means.reshape((4,1))
demeaned.mean()

np.float64(0.0)

In [ ]:
arr - arr.mean(1).reshape((4,1))


array([[-0.5014, -0.1555,  0.657 ],
       [ 0.2318, -0.1668, -0.065 ],
       [-0.5892, -0.6261,  1.2153],
       [-0.3211, -0.3487,  0.6697]])